# Generated by Django 4.2.6 on 2023-10-29 07:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_tag_category_courses_category_image_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
